
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus-rest
  description: A cool quarkus app
  annotations:
    argocd/app-name: my-quarkus-rest-bootstrap
    backstage.io/kubernetes-id: my-quarkus-rest
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: iocanel
    backstage.io/source-location: url:https://github.com/iocanel/my-quarkus-rest
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: my-quarkus-rest
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: iocanel/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
    app.quarkus.io/quarkus-version: "3.10"
  tags:
    - java
    - quarkus
  links:
    - url: https://my-quarkus-rest-iocanel.apps.qshift.snowdrop.dev/
      title: Quarkus application url
      icon: web
spec:
  type: service
  lifecycle: production
  owner: user:guest
